spring:
  datasource:
    url: jdbc:mysql://shift-database.mysql.database.azure.com:3306/moisoDatabase?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: moiso_user
    password: qwer1234!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true